language: go
go:
  - "1.10"
sudo: false
notifications:
  email: false
os:
  - linux
before_install:
  - npm install -g codeclimate-test-reporter
  - go get github.com/alecthomas/gometalinter
  - gometalinter --install
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
install:
  - dep ensure
script:
  - go build -race -gcflags "-N -l" ./plugin/persistence
  - go build -race -gcflags "-N -l" ./plugin/auth
  - go build -race -gcflags "-N -l" ./subscriber
  - go build -race -gcflags "-N -l" ./mqttp
  - go build -race -gcflags "-N -l" -buildmode=plugin ./plugin/debug
  - go build -race -gcflags "-N -l" -buildmode=plugin ./plugin/health
  - go build -race -gcflags "-N -l" -buildmode=plugin ./plugin/persistence/bbolt
  - gometalinter --fast --exclude=corefoundation.go --deadline=360s --enable-gc --sort=path --cyclo-over=40 --dupl-threshold=100 --disable=gotype --vendor --enable=goimports ./...
  - go test -race -coverprofile=coverage.txt -covermode=atomic -v $(go list ./... | grep -v /vendor/)
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - codeclimate-test-reporter < coverage.txt